"""
Domain Models — Product (SQLAlchemy 2.0).
Stores product data and the AI-generated "Sale Profile" in JSONB.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Product(Base):
    """
    A dropshipping product offered by the bot.

    The `sale_profile` JSONB field is generated by Stage 1 AI (Gemini Pro)
    and contains: key features, objection tree, pricing tiers, etc.
    """
    __tablename__ = "products"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(300), nullable=False)
    description_raw: Mapped[str | None] = mapped_column(Text)  # Admin input
    price: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), default="ARS")
    stock: Mapped[int] = mapped_column(default=0)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, index=True)
    image_url: Mapped[str | None] = mapped_column(String(500))
    whatsapp_link: Mapped[str | None] = mapped_column(Text) # Pre-generated wa.me link

    # ── AI-generated Sale Profile (Stage 1) ────────────────────────────────────
    # Structure (example):
    # {
    #   "key_features": [...],
    #   "target_audience": "...",
    #   "objection_tree": {"price_too_high": "...", ...},
    #   "pricing_tiers": [{"label": "promo", "price": 4999, "conditions": "..."}],
    #   "closing_script": "...",
    # }
    sale_profile: Mapped[dict | None] = mapped_column(JSONB)

    # ── Relationships ────────────────────────────────────────────────────────
    images: Mapped[list["ProductImage"]] = relationship(
        "ProductImage", back_populates="product", cascade="all, delete-orphan", lazy="selectin"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class ProductImage(Base):
    """
    Publicly available images forming a gallery per product.
    These can be requested and sent by the bot (Gemini Flash tool).
    """
    __tablename__ = "product_images"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    product_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("products.id", ondelete="CASCADE"), nullable=False, index=True
    )
    url: Mapped[str] = mapped_column(String(500), nullable=False)
    file_path: Mapped[str] = mapped_column(String(500), nullable=False)
    is_public: Mapped[bool] = mapped_column(Boolean, default=True, index=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # ── Relationships ────────────────────────────────────────────────────────
    product: Mapped["Product"] = relationship("Product", back_populates="images")
